### ISSUE TITLE
Support other payscales

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/pidash-ucamstaffoncosts#11]
Current university payscales should only be used when CHRIS datamart returns "Grade XX" as "GRADE". Retrieve from CHRIS datamart a report with the distribution on how many different type of entries for "GRADE" are for current non ended contracts. If sufficient, support "Clinical (StR)" and "Clinical (SpR)", and "MRC Band XX".

Store a copy of the report in our PIDashboard Google Drive folder: "Technical Documentation"

**Comment by rjw57** [comment]
Current contract grades sorted by popularity: https://docs.google.com/spreadsheets/d/1TocJB5q97dI3GLz21YL1acU9QqVbo-Ve0c8N9uGa-Bg/edit?usp=sharing

**Comment by abrahammartin** [comment]
https://www.hr.admin.cam.ac.uk/pay-benefits/salary-scales/clinical-research-associates-and-clinical-lecturers-including-costs

**Comment by abrahammartin** [comment]
Moving MRC Bands to #17
