### ISSUE TITLE
Missing pension scheme: "CPS (pre 2013)"

### ISSUE THREAD

**Issue by msb** [uisautomation/pidash-ucamstaffoncosts#6]
The spreadsheet https://docs.google.com/spreadsheets/d/1b37Qh1Z-Wp0a067Gmbq9HllQSE8qLjz_jpBdnj9A90Y/edit#gid=913486769 showing the pension schemes of research staff by popularity gives 9 pension schemes that make up 95% of the usage. Of these, only 2 pension schemes, "USS (CARE)" and "CPS (pre 2013)", aren't supported by this module. However, between them, they make up 13% of the entire membership and therefore it make sense to support them.

**Comment by rjw57** [comment]
There is also the MRC Pension (fixed at 15.9%)

**Comment by abrahammartin** [comment]
TASK UPDATE: Update the linked spreadsheet with new data from CHRIS datamart microservice. Only retrieve pension data from staff members with an end date in the future or a null end date (contract still active, person currently employed). Take into account that there are multiple possible end dates:
 CONTRACT_END_DATE, PERSON_LEAVING_DATE, FUNDING_EFF_END_DATE, EXP_OCC_END_DATE, ACTUAL_OCC_END_DATE.

After the spreadsheet has been updated, re-asses which pension schemes are missing that we should have to support.

**Comment by rjw57** [comment]
Now updated. I've highlighted the ones I think we should support which covers the vast majority (>99.5%) of the rows.

**Comment by abrahammartin** [comment]
Looks good to me

**Comment by rjw57** [comment]
Dropping USS (CARE) requirement because it's not relevant for current contracts.

**Comment by abrahammartin** [comment]
Update the dict in webapp to support the new pension schemes
